version: '3.8'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      # - ./certs:/certs
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 0919472035Az
      MYSQL_DATABASE: online-shop
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
