version: '3.8'

services:
  app:
    build: ./app
    container_name: capybara-app
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/firebase_key
    secrets:
      - firebase_key
    volumes:
      - ./app:/app
    restart: unless-stopped

secrets:
  firebase_key:
    file: ./app/serviceAccountKey.json
